### PR TITLE
Remove unused code from deps

### PR DESCRIPTION
**Pull request by ChALkeR**
@Sekhmet ~This is WiP, just to test code removals.~
~Currently points to not specific commits, but branches -- but that is for testing only.~

Could you please confirm that this still builds and works in RN for you?
About 9-10k lines removed here, I believe those were unused.

We could continue dropping stuff after that.

Related branches:
* https://github.com/ExodusMovement/monero-core-custom/tree/react-native-integration
* https://github.com/ExodusMovement/mymonero-core-cpp/tree/react-native-integration

### CODE REVIEW

**Comment by Sekhmet** [comment]
Everything seems to be working fine.
Tested syncing and sending on iOS without any issues.

**Comment by ChALkeR** [comment]
@Sekhmet Thanks! I will take another look to check if more code could be removed there.

**Comment by ChALkeR** [comment]
@Sekhmet I think this should be ready now. Could you please confirm that this works?

Related commits: https://github.com/ExodusMovement/mymonero-core-cpp/commit/b72e653363db1cb2d654bd5c21ab01bea31675a0, https://github.com/ExodusMovement/monero-core-custom/commit/36f6892dbe9fe6c7c87e8a52ca863c51f331fc7b.

**Comment by Sekhmet** [comment]
Confirmed to be working on iOS (simulator and device).
I will test Android as well and confirm again.

**Review by Sekhmet — APPROVED** [review]
tACK

Confirmed to work on:
- iOS simulator
- iOS device
- Android device

**Comment by Sekhmet** [comment]
Ain mentioned that we want to release this package to npm.
Do you want to take care of building binaries and publishing it yourself @ChALkeR ?

**Comment by ChALkeR** [comment]
@Sekhmet No, I would prefer this to be built from the dedicated release setup once this is merged and we finish with everything else.

**Pull request merged**
